openapi: '3.0.0'


servers:
  - url: 'https://btc.haskoin.com/api/'
  - url: 'https://bch.haskoin.com/api/'
  - url: 'https://btctest.haskoin.com/api/'
  - url: 'https://bchtest.haskoin.com/api/'


info:
  version: '0.16.2'
  title: Blockchain API
  contact:
    name: Haskoin
    url: http://haskoin.com
    email: xenog@protonmail.com
  license:
    name: Unlicense
    url: http://unlicense.org/


tags:
  - name: address
  - name: transaction
  - name: block
  - name: network
  
  
paths:
  '/health':
    get:
      tags:
        - network
      summary: get health status information
      operationId: healthCheck
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '503':
          description: unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
              example:
                headers:
                  height: 1283593
                  hash: '00000000000003ad033d7508575ea8f8fd4d9d5d331a9ecd22ab712bdbc35dbb'
                blocks:
                  height: 0
                  hash: '000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943'
                peers: 0
                net: bchtest
                ok: false
                synced: false
                version: '0.1.2'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/address/{address}/transactions':
    get:
      tags:
        - address
      summary: get transactions for an address
      operationId: getAddressTxs
      parameters:
        - $ref: '#/components/parameters/addressParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockTx'
                example:
                  - txid: '128d3979e1837631688d54a5e55716d44617ef70da1237042abcea51128d4ae2'
                    block:
                      height: 1283392
                      position: 1
                  - txid: '5d53eb8a24d02f7b92825ff1b2b68f478c9b0129e8bbc90e9a893b461086c6b7'
                    block:
                      height: 1283391
                      position: 1
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/address/{address}/transactions/full':
    get:
      tags:
        - address
      summary: get transactions for an address
      operationId: getAddressTxsFull
      parameters:
        - $ref: '#/components/parameters/addressParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/transactions':
    get:
      tags:
        - address
      summary: get transactions for multiple addresses
      operationId: getMultipleAddressTxs
      parameters:
        - $ref: '#/components/parameters/addressesParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockTx'
                example:
                  - txid: '128d3979e1837631688d54a5e55716d44617ef70da1237042abcea51128d4ae2'
                    block:
                      height: 1283392
                      position: 1
                  - txid: '5d53eb8a24d02f7b92825ff1b2b68f478c9b0129e8bbc90e9a893b461086c6b7'
                    block:
                      height: 1283391
                      position: 1
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/transactions/full':
    get:
      tags:
        - address
      summary: get transactions for multiple addresses
      operationId: getMultipleAddressTxsFull
      parameters:
        - $ref: '#/components/parameters/addressesParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/{address}/balance':
    get:
      tags:
        - address
      operationId: getBalance
      summary: get balance for an address
      parameters:
        - $ref: '#/components/parameters/addressParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/balances':
    get:
      tags:
        - address
      summary: get balances for multiple addresses
      operationId: getMultipleAddressBalances
      parameters:
        - $ref: '#/components/parameters/addressesParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Balance'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/{address}/unspent':
    get:
      tags:
        - address
      summary: get unspent outputs for an address
      operationId: getAddressUnspent
      parameters:
        - $ref: '#/components/parameters/addressParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unspent'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/unspent':
    get:
      tags:
        - address
      summary: get unspent outputs for multiple addresses
      operationId: getMultipleAddressUnspent
      parameters:
        - $ref: '#/components/parameters/addressesParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unspent'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: invalid address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/best':
    get:
      tags:
        - block
      summary: get best block in chain
      operationId: GetBlockHead
      parameters:
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/block/{block}':
    get:
      tags:
        - block
      operationId: getBlock
      summary: get block by hash
      parameters:
        - $ref: '#/components/parameters/notxParam'
        - $ref: '#/components/parameters/blockParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: block not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/blocks':
    get:
      tags:
        - block
      operationId: getBlocks
      summary: get multiple blocks by hash
      parameters:
        - $ref: '#/components/parameters/notxParam'
        - $ref: '#/components/parameters/blocksParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: block not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/height/{height}':
    get:
      tags:
        - block
      operationId: getBlocksAtHeight
      summary: get block hashes at specified height
      parameters:
        - $ref: '#/components/parameters/blockHeightParam'
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: block not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/heights':
    get:
      tags:
        - block
      operationId: getBlocksAtHeights
      summary: get multiple blocks at specified heights
      parameters:
        - name: heights
          in: query
          explode: false
          required: true
          schema:
            type: array
            example:
              - 1283393
            items:
              type: integer
        - $ref: '#/components/parameters/blockHeightsParam'
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: block not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transaction/{txid}':
    get:
      tags:
        - transaction
      operationId: getTransaction
      parameters:
        - $ref: '#/components/parameters/txidParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transaction/{txid}/hex':
    get:
      tags:
        - transaction
      operationId: getHexTransaction
      parameters:
        - $ref: '#/components/parameters/txidParam'
      responses:
        '200':
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
        '404':
          description: transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transaction/{txid}/bin':
    get:
      tags:
        - transaction
      operationId: getBinTransaction
      parameters:
        - $ref: '#/components/parameters/txidParam'
      responses:
        '200':
          description: success
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/transaction/{txid}/after/{height}':
    get:
      tags:
        - transaction
      operationId: cbAfterHeight
      summary: find out if transaction has a coinbase ancestor past height
      parameters:
        - $ref: '#/components/parameters/txidParam'
        - $ref: '#/components/parameters/blockHeightParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    description: transaction has a coinbase ancestor after height
                    type: boolean
                    nullable: true
                    example: true
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/transactions':
    get:
      tags:
        - transaction
      operationId: getTransactions
      parameters:
        - $ref: '#/components/parameters/txidsParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

    post:
      tags:
        - transaction
      operationId: postTransaction
      requestBody:
        description: transaction to publish
        content:
          text/plain:
            schema:
              type: string
              example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxId'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: invalid transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

        '500':
          description: server or network error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transactions/hex':
    get:
      tags:
        - transaction
      operationId: getHexTransactions
      parameters:
        - $ref: '#/components/parameters/txidsParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
        '404':
          description: transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transactions/bin':
    get:
      tags:
        - transaction
      operationId: getBinTransactions
      parameters:
        - $ref: '#/components/parameters/txidsParam'
      responses:
        '200':
          description: success
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/mempool':
    get:
      tags:
        - transaction
      operationId: getMempool
      parameters:
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - '8198a7924b0c4cc5d1b71e48b4f28e5106d2d536181d018acecb6e9f7ebce689'
                  - 'eed4160b9919901e7f55a93d5e9f1add5c7e56c930276532673105844c233b3f'
                  - 'cdb3793bb6c2669e01da5e8751d8975766c81fbce7bd9d7d08414b84448d3129'
                  - '870d7515f9ab782f7b84d3bf15d40e801b835d4abc5389f522d29e5ace223de9'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/events':
    get:
      tags:
        - block
        - transaction
      operationId: getEventStream
      responses:
        '200':
          description: stream
          content:
            application/x-json-stream:
              schema:
                $ref: '#/components/schemas/Event'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/peers':
    get:
      tags:
        - network
      operationId: getPeers
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peer'
                example:
                  - useragent: '/Bitcoin ABC:0.18.5(EB32.0)/'
                    address: '34.245.216.80:18333'
                    version: 70015
                    services: '0000000000000025'
                    relay: true
                  - useragent: '/Bitcoin SV:0.1.0(EB128.0)/'
                    address: '142.93.42.82:18333'
                    version: 70015
                    services: '0000000000000025'
                    relay: true
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/xpub/{xpub}':
    get:
      tags:
        - address
      operationId: getXPubSummary
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XPubSummary'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: invalid xpub
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/transactions/full':
    get:
      tags:
        - address
      operationId: getXPubTransactionsFull
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: invalid xpub
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/transactions':
    get:
      tags:
        - address
      operationId: getXPubTransactions
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockTx'
                example:
                  - block:
                      height: 765798
                      position: 6
                    txid: '534fedf9caf3323e4a08f17d813199a0b3f561b1c9d58ad4a50278a611e8a45d'
                  - block:
                      height: 765798
                      position: 5
                    txid: 'be45116b6f505a4d5d8fb17cfe12678f70e9ac2df003aae1ce89c37cbc034384'
                  - block:
                      height: 765798
                      position: 4
                    txid: '14288fc7465fa8c786fd19e31d163688ced5d66636e9f761b4e8e376f2421492'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: invalid xpub
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/balances':
    get:
      tags:
        - address
      operationId: getXPubBalances
      parameters:
        - $ref: '#/components/parameters/xpubParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XPubBalance'
                example:
                  - path: [1,8]
                    balance:
                      received: 199880000
                      utxo: 0
                      address: 'bchtest:qrmaylmr0t7ad0sg80nwdfw2ft5ysn3hccvhk5rp89'
                      txs: 2
                      unconfirmed: 0
                      confirmed: 0
                  - path: [1,9]
                    balance:
                      received: 199770000
                      utxo: 0
                      address: 'bchtest:qrta9zrumx2x9xlkj3ecxurpkv0zspv9xy7tlreccv'
                      txs: 2
                      unconfirmed: 0
                      confirmed: 0
                  - path: [1,10]
                    balance:
                      received: 199770000
                      utxo: 0
                      address: 'bchtest:qquvk7vrffk7m76x24tnr572mjpykghhg5fjptsjs6'
                      txs: 2
                      unconfirmed: 0
                      confirmed: 0
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: invalid xpub
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/unspent':
    get:
      tags:
        - address
      operationId: getXPubUnspent
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/posParam'
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XPubUnspent'
                example:
                  - path: [0,1959]
                    unspent:
                      pkscript: '76a914a7ec2ca3345ebe30c265bab1f4bbfb0e7716727288ac'
                      value: 1000000
                      address: 'bchtest:qzn7ct9rx30tuvxzvkatra9mlv88w9njwg0p0gqkjv'
                      block:
                        height: 1096570
                        position: 9
                      index: 0
                      txid: '717c7732a6e30c7a06b3c0f5eac040878d6e6f91e17c2471d38eb28050af8cac'
                  - path: [0,1792]
                    unspent:
                      pkscript: '76a91472dbe14842d2e6d7da1c03e81012a9835c6c646488ac'
                      value: 10000
                      address: 'bchtest:qpedhc2ggtfwd476rsp7syqj4xp4cmryvs98s3w6u2'
                      block:
                        height: 1092503
                        position: 12
                      index: 1
                      txid: '2733fcd7d55f5f7696e18f1eaaa5f9970cd88e063af4775e4139f1eb5482a856'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: invalid xpub
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
                
                
components:
  schemas:
  
    BlockRef:
      oneOf:
        - $ref: '#/components/schemas/Block'
        - $ref: '#/components/schemas/Mempool'
      example:
        mempool: 1548766186903

    Block:
      type: object
      required:
        - height
        - position
      properties:
        height:
          description: height of block
          type: integer
          example: 1283393
        position:
          description: position of transaction within block
          type: integer
          example: 2

    Mempool:
      type: object
      required:
        - mempool
      properties:
        mempool:
          description: time transaction was received in mempool
          type: integer
          format: int64
          example: 1548766187

    XPubBalance:
      type: object
      required:
        - path
        - balance
      properties:
        path:
          description: derivation path (non-hardened)
          type: array
          items:
            type: integer
          example: [1, 10]
        balance:
          $ref: '#/components/schemas/Balance'

    XPubUnspent:
      type: object
      required:
        - path
        - unspent
      properties:
        path:
          description: derivation path (non-hardened)
          type: array
          items:
            type: integer
          example: [1, 10]
        unspent:
          $ref: '#/components/schemas/Unspent'

    XPubSummary:
      type: object
      required:
        - balance
        - indices
        - paths
        - txs
      properties:
        balance:
          type: object
          required:
            - received
            - confirmed
            - unconfirmed
          properties:
            recived:
              type: integer
            confirmed:
              type: integer
            unconfirmed:
              type: integer
        indices:
          type: object
          required:
            - external
            - change
          properties:
            external:
              type: integer
            change:
              type: integer
        paths:
          type: object
          additionalProperties:
            type: array
            items:
              type: integer
          example:
            'bchtest:qrmaylmr0t7ad0sg80nwdfw2ft5ysn3hccvhk5rp89': [1, 8]
            'bchtest:qrta9zrumx2x9xlkj3ecxurpkv0zspv9xy7tlreccv': [1, 9]
            'bchtest:qquvk7vrffk7m76x24tnr572mjpykghhg5fjptsjs6': [1, 10]
        txs:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'

    BlockTx:
      type: object
      required:
        - block
        - txid
      properties:
        block:
          $ref: '#/components/schemas/BlockRef'
        txid:
          type: string
          example: '534fedf9caf3323e4a08f17d813199a0b3f561b1c9d58ad4a50278a611e8a45d'

    Balance:
      type: object
      required:
        - address
        - confirmed
        - unconfirmed
        - utxo
        - received
        - txs
      properties:
        address:
          type: string
          example: 'bchtest:qrr724dvaz5kdhujv52urdrwv0hy4jxpusgspun650'
        confirmed:
          type: integer
          format: int64
          description: sum of confirmed unspent output values
          example: 0
        unconfirmed:
          type: integer
          format: int64
          description: sum of unconfirmed unspent output values
          example: 0
        utxo:
          description: number of unspent outputs
          type: integer
          format: int64
          example: 0
        received:
          description: total received by this address
          type: integer
          format: int64
          example: 4013201
        txs:
          description: count of transactions affecting this address
          type: integer
          format: int64
          example: 2

    Unspent:
      type: object
      required:
        - address
        - block
        - txid
        - index
        - pkscript
        - value
      properties:
        address:
          type: string
          nullable: true
          example: 'qq235k7k9y5cwf3s2vfpxwgu8c5497sxnsdnxv6upc'
        block:
          $ref: '#/components/schemas/BlockRef'
        txid:
          type: string
          example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'
        index:
          type: integer
          example: 0
        pkscript:
          type: string
          example: '76a914151a5bd62929872630531213391c3e2952fa069c88ac'
        value:
          type: integer
          format: int64
          description: output value in satoshi
          example: 4005704

    BlockData:
      type: object
      required:
        - hash
        - height
        - mainchain
        - previous
        - time
        - version
        - bits
        - nonce
        - size
        - tx
        - merkle
        - subsidy
        - fees
        - outputs
      properties:
        hash:
          type: string
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'
        size:
          type: integer
          example: 722
        height:
          type: integer
          example: 1283393
        mainchain:
          type: boolean
          example: true
        previous:
          type: string
          example: '000000000000024005a247066be86876777cd84f5bbbc21ba02d32e7822c2fb9'
        time:
          type: integer
          format: int64
          example: 1548766137
        version:
          type: integer
          format: int64
          example: 536870912
        bits:
          type: integer
          format: int64
          example: 437016577
        nonce:
          type: integer
          format: int64
          example: 12019207
        tx:
          type: array
          example:
            - '17106222f0c49ff2553e0fe39966d6fbd08b1d5ea3ef5b2359d94a69846b50fc'
            - '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
            - 'ce0b0d3ac21b91f24b5b0fc8f057071656496aa898fa7ee01f6b1f7d9b169a9a'
          items:
            type: string
        merkle:
          type: string
          example: '76999ce20135a02df2d7a7a78282fd748b8804b76a817a25ced05f1cf4f2d2a5'
        subsidy:
          type: integer
          format: int64
          description: block subsidies
          example: 78125000
        fees:
          type: integer
          format: int64
          description: transaction fees
          example: 115499
        outputs:
          type: integer
          format: int64
          description: all outputs
          example: 470103316006
        weight:
          type: integer
          description: block weight for segwit networks

    Input:
      type: object
      required:
        - coinbase
        - txid
        - output
        - sigscript
        - sequence
        - pkscript
        - value
        - address
      properties:
        coinbase:
          type: boolean
          example: false
        txid:
          type: string
          example: '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
        output:
          type: integer
          example: 0
        sigscript:
          type: string
          example: '483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006c'
        value:
          type: integer
          format: int64
          nullable: true
          example: 4008203
        sequence:
          type: integer
          format: int64
          example: 4294967294
        address:
          type: string
          nullable: true
          example: 'bchtest:qzyrvsm6z4ucrhaq4zza3wylre7mavvldgr67jrxt4'
        pkscript:
          type: string
          nullable: true
          example: '76a9148836437a157981dfa0a885d8b89f1e7dbeb19f6a88ac'
        witness:
          description: witness data on segwit networks
          type: array
          example: []
          items:
            type: string

    Spender:
      type: object
      required:
        - txid
        - input
      properties:
        txid:
          type: string
          example: '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
        input:
          type: integer
          example: 0

    Output:
      type: object
      required:
        - address
        - pkscript
        - value
        - spent
      properties:
        address:
          type: string
          nullable: true
          example: 'bchtest:qzy3e4pnrglcd3ump5ndqrwu5qv2j8szcv6extyerq'
        pkscript:
          type: string
          example: '76a914891cd4331a3f86c79b0d26d00ddca018a91e02c388ac'
        value:
          type: integer
          format: int64
          example: 4010702
        spent:
          type: boolean
          example: true
        spender:
          $ref: '#/components/schemas/Spender'

    Transaction:
      type: object
      required:
        - txid
        - size
        - version
        - locktime
        - fee
        - inputs
        - outputs
        - block
        - deleted
        - time
      properties:
        txid:
          type: string
          example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'
        size:
          type: integer
          example: 245
        version:
          type: integer
          format: int64
          example: 1
        locktime:
          type: integer
          format: int64
          example: 0
        fee:
          type: integer
          format: int64
          example: 2499
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/Input'
          example:
            - pkscript: '76a9148836437a157981dfa0a885d8b89f1e7dbeb19f6a88ac'
              value: 4008203 
              address: 'bchtest:qzyrvsm6z4ucrhaq4zza3wylre7mavvldgr67jrxt4'
              sequence: 4294967294
              output: 0
              sigscript: '483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006c'
              coinbase: false
              txid: '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/Output'
          example:
            - spent: true
              pkscript: '76a914151a5bd62929872630531213391c3e2952fa069c88ac'
              value: 4005704
              address: 'bchtest:qq235k7k9y5cwf3s2vfpxwgu8c5497sxnsdnxv6upc'
              spender:
                input: 0
                txid: 'f1173bb9269c5f7da1e188fae7b6295f3ed4d2861fbd45f4b5415f5bbe06d8ae'
            - spent: false
              pkscript: '6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c30'
              value: 0
              address: null
        block:
          $ref: '#/components/schemas/BlockRef'
        deleted:
          type: boolean
          example: false
        time:
          type: integer
          format: int64
          example: 1548767230
        rbf:
          type: boolean
          example: false
          description: transaction vulnerable to replace-by-fee
        weight:
          type: integer
          example: 980
          description: transaction weight for segwit networks

    Event:
      type: object
      required:
        - type
        - id
      properties:
        type:
          type: string
          enum:
            - tx
            - block
          example: block
        id:
          type: string
          description: block or transaction id
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

    Peer:
      type: object
      required:
        - useragent
        - address
        - version
        - services
        - relay
      properties:
        useragent:
          type: string
          example: '/Bitcoin ABC:0.18.4(EB32.0)/'
        address:
          type: string
          example: '34.253.51.235:18333'
        version:
          type: integer
          example: 70015
        services:
          type: string
          example: '0000000000000025'
        relay:
          type: boolean
          example: true

    HealthCheck:
      type: object
      required:
        - headers
        - blocks
        - peers
        - net
        - ok
        - synced
        - version
      properties:
        headers:
          type: object
          required:
            - hash
            - height
          properties:
            hash:
              type: string
              nullable: true
              example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'
            height:
              type: integer
              nullable: true
              example: 1283393
        blocks:
          type: object
          required:
            - hash
            - height
          properties:
            hash:
              type: string
              nullable: true
              example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'
            height:
              type: integer
              nullable: true
              example: 1283393
        peers:
          type: integer
          nullable: true
          example: 20
        net:
          type: string
          example: bchtest
        ok:
          type: boolean
          example: true
        synced:
          type: boolean
          example: true
        version:
          type: string
          example: '0.1.2'
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    TxId:
      type: object
      required:
        - txid
      properties:
        txid:
          type: string
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

  parameters:

    addressParam:
      name: address
      in: path
      required: true
      schema:
        type: string
        example: 'qrr724dvaz5kdhujv52urdrwv0hy4jxpusgspun650'

    addressesParam:
      name: addresses
      in: query
      explode: false
      required: true
      schema:
        type: array
        items:
          type: string
          example: 'qrr724dvaz5kdhujv52urdrwv0hy4jxpusgspun650'

    limitParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      description: maximum number of entries to return

    heightParam:
      name: height
      in: query
      required: false
      schema:
        type: integer
      description: highest block to return objects from (not to be used with offset or time parameters)

    posParam:
      name: pos
      in: query
      required: false
      schema:
        type: integer
      description: highest transaction position at block specified by height parameter to return objects from (must specify height)

    timeParam:
      name: time
      in: query
      required: false
      schema:
        type: integer
        format: int64
      description: highest unix timestamp from where to start returning mempool objects (not compatible with height/pos or offset parameters)

    offsetParam:
      name: offset
      in: query
      required: false
      schema:
        type: integer
      description: skip this many objects (not to be used with height/pos or time parameters)

    notxParam:
      name: notx
      in: query
      required: false
      schema:
        type: boolean
      description: do not include block transactions (only coinbase)

    blockParam:
      name: block
      in: path
      required: true
      schema:
        type: string
      example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

    blocksParam:
      name: blocks
      in: path
      explode: false
      required: true
      schema:
        type: array
        items:
          type: string
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

    blockHeightParam:
      name: height
      in: path
      required: true
      schema:
        type: integer
        example: 1283393

    blockHeightsParam:
      name: heights
      in: query
      explode: false
      required: true
      schema:
        type: array
        example:
          - 1283393
        items:
          type: integer

    txidParam:
      name: txid
      in: path
      required: true
      schema:
        type: string
        example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'

    txidsParam:
      name: txids
      in: query
      explode: false
      required: true
      schema:
        type: array
        items:
          type: string
          example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'

    xpubParam:
      name: xpub
      in: path
      required: true
      schema:
        type: string
        example: tpubD8XsNAGEy3Pzeeq6hmbRjwrP7G6Goobw4jWvu68tKzxDSFE5VmgpKoDeSFjnmgCLPrijuQwHVodUv7oZDqPNJbzC4mxZStZisGAEwgbpccH
